In [9]:
import sys
import numpy as np
from Analysis import transform_data, load_data , load_model , make_predictions, display_metrics

# Loading Data and Models

In [10]:
clf = load_model('../Saved_Models/svm_model.joblib')
pca = load_model('../Saved_Models/pca.joblib')
x_val = load_data('../Feature_Extraction_Selection/x_val.npy')
y_val = load_data('../Feature_Extraction_Selection/y_val.npy')

# Transforming The Feature

In [11]:
features_pca = transform_data(pca, x_val)

# Predicting

In [12]:
y_pred = make_predictions(clf, features_pca)
display_metrics(y_val, y_pred)

Validation accuracy: 96.50%
Confusion Matrix:
 [[49  0  0  1]
 [ 0 50  0  0]
 [ 2  0 46  2]
 [ 2  0  0 48]]
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.98      0.95        50
           1       1.00      1.00      1.00        50
           2       1.00      0.92      0.96        50
           3       0.94      0.96      0.95        50

    accuracy                           0.96       200
   macro avg       0.97      0.96      0.97       200
weighted avg       0.97      0.96      0.97       200

